version: "2"


volumes:
  txpfiles:
  txpimages:
  mysql:

networks:
  frontend:
  backend:

services:
  txp:
    container_name: txp-web
    restart: always
    build: .
    # image: garyritchie/docker-textpattern
    depends_on:
      - db
    ports:
      - "80:80"
    # links:
    #   - db
    networks:
      - backend
      - frontend
    volumes:
      - txpfiles:/var/www/html/files
      - txpimages:/var/www/html/images
      - /etc/localtime:/etc/localtime:ro
      # - data:/var/www/html/textpattern/config.php
    environment:
      - TZ=America/New_York

  db:
    container_name: txp-db
    restart: always
    # build: mysql/.
    image: mysql:5.6
    # ports:
    #   - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=txproot
      - MYSQL_DATABASE=txp
      - TZ=America/New_York
